
server:
  port: 8080
  jsp-servlet:
    init-parameters:
      development: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: #해당 db url
    username: #db계정
    password: #db계정 비밀번호

vworld:
  apiKey: E375A39D-7B0F-39D2-ADDD-97066A55263A



#server.servlet.session.timeout = 600
#spring.main.allow-bean-definition-overriding=true

# MyBatis
# mapper.xml 위치 지정
mybatis:
  mapper-locations: mapper/*.xml
  # model 프로퍼티 camel case 설정
  configuration:
    map-underscore-to-camel-case: true
  # 패키지 명을 생략할 수 있도록 alias 설정
  type-aliases-package: com.lee.hjboard

# mapper 로그레벨 설정
logging:
  level: debug
  level.com.azurealstn.codespringweb.mapper: TRACE


